/**
 * Emits the released `/stream` method-name set for the host stream RPC registry -
 * the sorted `Object.keys(hostStreamRpcRegistry)` (the handshake-visible stream
 * method names, without serializing every method's schemas).
 *
 * The committed snapshot
 * (`src/host/__tests__/__fixtures__/released-stream-method-names.ts`) freezes
 * the browser V1 stream method-name set. `released-stream-surface-compat.test.ts`
 * fails if a stream method name is added or removed unexpectedly. New browser
 * capabilities should evolve `browser.sessions` / `browser.screencast`
 * additively within major 1, not by adding parallel stream names.
 *
 * Regenerate ONLY for a coordinated stream baseline change - the resulting diff
 * is the reviewable record of that decision:
 *
 *   bun run protocol/scripts/snapshot-released-stream-method-names.ts > \
 *     protocol/src/host/__tests__/__fixtures__/released-stream-method-names.ts
 */
import { hostStreamRpcRegistry } from "@traycer/protocol/host/index";

const header =
  "// AUTO-GENERATED by protocol/scripts/snapshot-released-stream-method-names.ts - do not edit by hand.\n" +
  "// The browser V1 /stream method-name set; frozen by released-stream-surface-compat.test.ts.\n";
const names = Object.keys(hostStreamRpcRegistry).sort();

process.stdout.write(
  `${header}export const releasedStreamMethodNames: readonly string[] = [\n${names
    .map((name) => `  ${JSON.stringify(name)},`)
    .join("\n")}\n];\n`,
);
