// AUTO-GENERATED by protocol/scripts/snapshot-released-stream-method-names.ts - do not edit by hand.
// The browser V1 /stream method-name set; frozen by released-stream-surface-compat.test.ts.
export const releasedStreamMethodNames: readonly string[] = [
  "agent.inbox.subscribe",
  "browser.screencast",
  "browser.sessions",
  "chat.subscribe",
  "epic.subscribe",
  "git.subscribeStatus",
  "migration.run",
  "notifications.subscribe",
  "resources.subscribe",
  "speech.dictate",
  "terminal.subscribe",
  "worktree.deleteByPath",
];
